CREATE TABLE IF NOT EXISTS dws_ct_contract_settlement_inventory_details_df(
    org_code STRING COMMENT '行政单位编码', 
    org_name STRING COMMENT '行政单位名称', 
    project_code STRING COMMENT '项目编码', 
    project_name  STRING COMMENT '项目名称', 
    project_shortname STRING COMMENT '项目简称',
    project_state_name STRING COMMENT '项目状态',
    contract_code  STRING COMMENT '集团合同编码',
    qy_contract_code STRING COMMENT '企业合同编码', 
    contract_name STRING COMMENT '合同名称', 
    employee_name STRING COMMENT '经办人', 
    dept_name STRING COMMENT '经办部门', 
    business_date STRING COMMENT '签订日期', 
    customer_id STRING COMMENT '对方单位id', 
    customer_name STRING COMMENT '对方单位名称（甲方名称）', 
    contract_valuation_type STRING COMMENT '合同计价id', 
    contract_valuation_type_code STRING COMMENT '合同计价编码', 
    contract_valuation_type_name  STRING COMMENT '合同计价名称',
    actual_amount  DECIMAL(24,2) COMMENT '合同金额',
    actual_tax_amount  DECIMAL(24,2) COMMENT '合同金额(含税)',
    settlement_status  STRING COMMENT '是否结算',
    settle_amount  DECIMAL(24,2) COMMENT '结算金额', 
    end_date  STRING COMMENT '竣工时间',
    tax_rate  STRING COMMENT '承包合同税率',
    fpdm    STRING COMMENT '发票代码',
    kp_time  STRING COMMENT '开票日期',
    kp_amount  DECIMAL(24,2) COMMENT '累计开票金额',
    kp_amount_detail  DECIMAL(24,2) COMMENT '累计开票金额',
    unbilled_amount  DECIMAL(24,2) COMMENT '未开票金额',
    remaining_settle_amount  DECIMAL(24,2) COMMENT '剩余结算', -- 未开票金额/（1+税率）
    payments_received  DECIMAL(24,2) COMMENT '已收款金额',
    payments_received_detail  DECIMAL(24,2) COMMENT '已收款金额明细',
    unpayments_received  DECIMAL(24,2) COMMENT '未收款金额',
    latest_received_time  STRING COMMENT '末次收款时间',
    djzt STRING COMMENT'单据状态',
    kxmc STRING COMMENT'款项性质名称',
    yfje DECIMAL(24,2) COMMENT'应付款金额',
    jsje DECIMAL(24,2) COMMENT'结算金额',
    zkje DECIMAL(24,2) COMMENT'暂时性扣款金额',
    zgjsje DECIMAL(24,2) COMMENT'暂估结算金额',
    fhkje  DECIMAL(24,2) COMMENT'返还款项金额',
    yjkkje DECIMAL(24,2) COMMENT'永久扣款金额',
    sjzkje DECIMAL(24,2) COMMENT'实际暂扣款金额',
    yfkje  DECIMAL(24,2) COMMENT'预付款金额',
    start_date STRING COMMENT '合同开工日期',
    sum_reply_tax_mny DECIMAL(24,2) COMMENT'产值',
    reply_tax_mny_detail DECIMAL(24,2) COMMENT'产值明细',
    last_modified_time  STRING COMMENT '最近修改时间',
    inner_code  STRING  comment'内部编码'
)
COMMENT '承包合同结算盘点明细表' -- 表的描述信息
PARTITIONED BY ( -- 按日期进行分区存储
    dt STRING COMMENT '日期分区'
)
STORED AS ORC ;