-- 创建原始表，并清空表
CREATE TABLE IF NOT EXISTS `zhaogang_test`.`rdos_batch_task` (
  `id` int(11) DEFAULT NULL COMMENT '主键',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户id',
  `project_id` int(11) DEFAULT NULL COMMENT '项目id',
  `node_pid` int(11) DEFAULT NULL COMMENT '父文件夹id',
  `name` varchar(255) DEFAULT NULL COMMENT '任务名称',
  `task_type` tinyint(4) DEFAULT NULL COMMENT '任务类型 -1:虚节点,0:sparksql,1:spark,2:数据同步,3:pyspark,4:R,5:深度学习,6:python,7:shell,8:机器学习,9:hadoopMR,10:工作流,12:carbonSQL,13:notebook,14:算法实验,15:libra sql,16:kylin,17:hiveSQL',
  `engine_type` tinyint(4) DEFAULT NULL COMMENT '执行引擎类型 0:flink,1:spark,2:datax,3:learning,4:shell,5:python2,6:dtyarnshell,7:python3,8:hadoop,9:carbon,10:postgresql,11:kylin,12:hive',
  `compute_type` tinyint(4) DEFAULT NULL COMMENT '计算类型 0实时，1 离线',
  `sql_text` text COMMENT 'sql 文本',
  `task_params` text COMMENT '任务参数',
  `schedule_conf` text COMMENT '调度配置 json格式',
  `period_type` tinyint(4) DEFAULT NULL COMMENT '周期类型',
  `schedule_status` tinyint(4) DEFAULT NULL COMMENT '0未开始,1正常调度,2暂停',
  `submit_status` tinyint(4) DEFAULT NULL COMMENT '0未提交,1已提交',
  `gmt_create` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `gmt_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_user_id` int(11) DEFAULT NULL COMMENT '最后修改task的用户',
  `create_user_id` int(11) DEFAULT NULL COMMENT '新建task的用户',
  `owner_user_id` int(11) DEFAULT NULL COMMENT '负责人id',
  `version` int(11) DEFAULT NULL COMMENT 'task版本',
  `is_deleted` tinyint(4) DEFAULT NULL COMMENT '0正常 1逻辑删除',
  `task_desc` text,
  `main_class` varchar(500) DEFAULT NULL,
  `exe_args` text,
  `flow_id` int(11) DEFAULT NULL COMMENT '工作流id',
  `use_other` int(11) DEFAULT NULL COMMENT '是否引用其他内容: 1-使用模板 2-使用组件 3-否',
  `component_version` varchar(100) DEFAULT NULL COMMENT '组件版本',
  `component_id` int(11) DEFAULT NULL COMMENT '使用的组件版本id',
  `yarn_resource_id` int(11) DEFAULT NULL COMMENT '任务指定的资源组id',
  `agent_resource_id` int(11) DEFAULT NULL COMMENT '任务指定的agent资源id',
  `depend_on_settings` tinyint(4) DEFAULT NULL COMMENT '依赖设置  0-手动依赖 1-自动推荐',
  `calender_id` int(11) DEFAULT NULL COMMENT '任务自定义调度日历id',
  `task_group` tinyint(4) DEFAULT NULL COMMENT '0: 周期任务,1:手动任务',
  `sort` int(11) DEFAULT NULL COMMENT '排序权重',
  `chosen_database` varchar(100) DEFAULT NULL COMMENT '任务手动选择的schema',
  `prod_task_id` int(11) DEFAULT NULL COMMENT '生产项目任务id',
  `remote_file_name` varchar(255) DEFAULT NULL COMMENT '旧任务名称，用于git任务重命名',
  `identity` varchar(100) DEFAULT NULL COMMENT '多集群运行的数据源id',
  `data_source_type` int(11) DEFAULT NULL COMMENT '数据源类型',
  `dt` varchar(50) DEFAULT NULL COMMENT '分区'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='离线任务表';

TRUNCATE TABLE `zhaogang_test`.`rdos_batch_task`;